###### MAPS Phenology #######
### Script name: Step9_CompareModels.R
## Author(s): XXX (removed for peer review)

########## Objective/Description of Script #####################
# Compare species models with exact GP, approximate GP and no GP
# Do comparisons within decision window and long-term window models
# Use loo package and elpd for model comparison
#################################################################

#### Setup ####
# load packages
library(tidyverse)
library(here)
library(brms)
library(posterior)
library(rstan)
library(loo)

# clear the environment to free up memory
rm(list = ls(all.names = TRUE))

#######################################################################################
############################## Decision window models #################################

# import decision window models
dw_sppmodels <- readRDS(here("Models/Model Outputs", "dw_sppmodels.rds")) %>%
  select(SPEC, dw_model) # models with exact gaussian process
dw_sppmodels_noGP <- readRDS(here("Models/Model Outputs", "dw_sppmodels_noGP.rds")) %>%
  select(SPEC, dw_model) %>% rename(dw_noGP_model = dw_model) # models with no gaussian process
dw_sppmodels_k20 <- readRDS(here("Models/Model Outputs", "dw_sppmodels_k20.rds")) %>%
  select(SPEC, dw_model) %>% rename(dw_k20_model = dw_model) # models with approximate gaussian process

# put the decision window models together into a single df
dwmodels_df <- left_join(dw_sppmodels, dw_sppmodels_noGP) %>%
  left_join(., dw_sppmodels_k20)

# use loo package to perform PSIS-loocv on the decision window models
# set moment_match = T to implement moment matching for models with high Pareto K values
dwmodels_loo <- dwmodels_df %>%
  mutate(dw_loo = purrr::map(dw_model, ~loo::loo(.x, save_psis = T, moment_match = T)),
         dw_noGP_loo = purrr::map(dw_noGP_model, ~loo::loo(.x, save_psis = T, moment_match = T)),
         dw_k20_loo = purrr::map(dw_k20_model, ~loo::loo(.x, save_psis = T, moment_match = T)),
         dw_loo_comp = purrr::pmap(list(dw_loo, dw_noGP_loo, dw_k20_loo), # use pmap to perform loo_compare across 3 models
                          \(dw_loo, dw_noGP_loo, dw_k20_loo)
                loo::loo_compare(dw_loo, dw_noGP_loo, dw_k20_loo))) %>%
  select(-dw_model, -dw_noGP_model, -dw_k20_model)

# export and save
saveRDS(dwmodels_loo, here("Models/Model Outputs", "dwmodels_loo.rds"))

# WOTH and NOCA for dw_k20_loo still have high pareto k values. Need to use reloo
# I did not run this step as these models have so many divergent transitions that they are not going to work as a "final" model
# we can reconsider if this model (approximate GP) has a lot of support in the next step

# obtain ELPD and SE of ELPD for the 3 models for each species
dw_elpd_SE <- dwmodels_loo %>%
  mutate(dw_elpd = purrr::map(dw_loo, ~ pluck(., 1, 1)), # extract elpd for DW model with exact GP
         dw_SE_elpd = purrr::map(dw_loo, ~ pluck(., 1, 4)), # extract SE of elpd for DW model with exact GP
         dw_noGP_elpd = purrr::map(dw_noGP_loo, ~ pluck(., 1, 1)), # extract elpd for DW model with no GP
         dw_noGP_SE_elpd = purrr::map(dw_noGP_loo, ~ pluck(., 1, 4)), # extract se of elpd for DW model with no GP
         dw_k20_elpd = purrr::map(dw_k20_loo, ~ pluck(., 1, 1)), # extract elpd for DW model with approximate GP where k = 20 and c = 5/4
         dw_k20_SE_elpd = purrr::map(dw_k20_loo, ~ pluck(., 1, 4)), # extract SE of elpd for DW model with approximate GP where k = 20 and c = 5/4
         elpd_diff = purrr::map(dw_loo_comp, ~ pluck(., 2)), # extract the elpd diff value generated by loo_compare(). This will be between the top and 2nd choice model
         SE_diff = purrr::map(dw_loo_comp, ~ pluck(., 5))) %>% # extract the SE of elpd diff generated by loo_compare(). This will be between the top and 2nd choice model
  select(-dw_loo, -dw_noGP_loo, -dw_k20_loo, -dw_loo_comp) # remove certain columns
  
View(dw_elpd_SE)
# no obvious differences between the 3 models
# conclusion: proceed with the non-spatial model with no GP for parsimony (and because our models have modest sample sizes)

saveRDS(dw_elpd_SE, here("Models/Model Outputs", "dw_elpd_SE.rds"))


#######################################################################################
############################## Long-term window models ################################
# clear the environment to free up memory
rm(list = ls(all.names = TRUE))

# import long-term window models
lw_sppmodels <- readRDS(here("Models/Model Outputs", "lw_sppmodels.rds")) %>%
  select(SPEC, lw_model) # models with exact gaussian process
lw_sppmodels_noGP <- readRDS(here("Models/Model Outputs", "lw_sppmodels_noGP.rds")) %>%
  select(SPEC, lw_model) %>% rename(lw_noGP_model = lw_model) # models with no gaussian process
lw_sppmodels_k20 <- readRDS(here("Models/Model Outputs", "lw_sppmodels_k20.rds")) %>%
  select(SPEC, lw_model) %>% rename(lw_k20_model = lw_model) # models with approximate gaussian process

# put the long-term window models together into a single df
lwmodels_df <- left_join(lw_sppmodels, lw_sppmodels_noGP) %>%
  left_join(., lw_sppmodels_k20)

# use loo package to perform PSIS-loocv on the long-term window models
# set moment_match = T to implement moment matching for models with high Pareto K values
lwmodels_loo <- lwmodels_df %>%
  mutate(lw_loo = purrr::map(lw_model, ~loo::loo(.x, save_psis = T, moment_match = T)),
         lw_noGP_loo = purrr::map(lw_noGP_model, ~loo::loo(.x, save_psis = T, moment_match = T)),
         lw_k20_loo = purrr::map(lw_k20_model, ~loo::loo(.x, save_psis = T, moment_match = T)),
         lw_loo_comp = purrr::pmap(list(lw_loo, lw_noGP_loo, lw_k20_loo), # use pmap to perform loo_compare across 3 models
                                   \(lw_loo, lw_noGP_loo, lw_k20_loo)
                                   loo::loo_compare(lw_loo, lw_noGP_loo, lw_k20_loo))) %>%
  select(-lw_model, -lw_noGP_model, -lw_k20_model)

saveRDS(lwmodels_loo, here("Models/Model Outputs", "lwmodels_loo.rds"))

# WOTH, WIWA, SOSP for lw k20 model still have high Pareto K values. We need to use reloo on them
# I did not run this step as these models have so many divergent transitions that they are not going to work as a "final" model

# obtain ELPD and SE of ELPD for the 3 models for each species
lw_elpd_SE <- lwmodels_loo %>%
  mutate(lw_elpd = purrr::map(lw_loo, ~ pluck(., 1, 1)), # extract elpd for LW model with exact GP
         lw_SE_elpd = purrr::map(lw_loo, ~ pluck(., 1, 4)), # extract SE of elpd for LW model with exact GP
         lw_noGP_elpd = purrr::map(lw_noGP_loo, ~ pluck(., 1, 1)), # extract elpd for LW model with no GP
         lw_noGP_SE_elpd = purrr::map(lw_noGP_loo, ~ pluck(., 1, 4)), # extract se of elpd for LW model with no GP
         lw_k20_elpd = purrr::map(lw_k20_loo, ~ pluck(., 1, 1)), # extract elpd for LW model with approximate GP where k = 20 and c = 5/4
         lw_k20_SE_elpd = purrr::map(lw_k20_loo, ~ pluck(., 1, 4)), # extract SE of elpd for LW model with approximate GP where k = 20 and c = 5/4
         elpd_diff = purrr::map(lw_loo_comp, ~ pluck(., 2)), # extract the elpd diff value generated by loo_compare(). This will be between the top and 2nd choice model
         SE_diff = purrr::map(lw_loo_comp, ~ pluck(., 5))) %>% # extract the SE of elpd diff generated by loo_compare(). This will be between the top and 2nd choice model
  select(-lw_loo, -lw_noGP_loo, -lw_k20_loo, -lw_loo_comp)  # remove certain columns
 l
saveRDS(lw_elpd_SE, here("Models/Model Outputs", "lw_elpd_SE.rds"))

View(lw_elpd_SE)
# no obvious differences between the 3 models
# conclusion: proceed with the non-spatial model with no GP for parsimony (and because our models have modest sample sizes)

