###### MAPS Phenology #######
### Script name: Step9_DWLWModelComparison.R
## Author(s): SLJ

########## Objective/Description of Script #####################
# this script compares the long-term and decision window model for each species using the loo package
# we do this using two model comparison metrics: ELPD and waic
#################################################################

#### Setup ####
# load packages
library(tidyverse)
library(here)
library(brms)
library(posterior)
library(rstan)
library(loo)

# clear the environment to free up memory
rm(list = ls(all.names = TRUE))

# import decision window models
dw_sppmodels <- readRDS(here("Models/Model Outputs", "dw_sppmodels.rds")) %>%
  select(SPEC, dw_model)

# import long-term window models
lw_sppmodels <- readRDS(here("Models/Model Outputs", "lw_sppmodels.rds")) %>%
  select(SPEC, lw_model)

# put the two models together into a single df
models_df <- left_join(dw_sppmodels, lw_sppmodels)

# use loo package to perform PSIS-loocv on the decision window and long-term models
# set moment_match = T to implement moment matching for models with high Pareto K values
models_loo <- models_df %>%
  mutate(dw_loo = purrr::map(dw_model, ~loo::loo(.x, save_psis = T, moment_match = T)),
         lw_loo = purrr::map(lw_model, ~loo::loo(.x, save_psis = T, moment_match = T)),
         loo_comp = purrr::map2(.x=dw_loo, .y=lw_loo, ~loo::loo_compare(.x, .y))) %>%
  select(-dw_model, -lw_model)

# obtain ELPD and SE of ELPD for the decision window and long term model for each species
elpd_SE <- models_loo %>%
  mutate(dw_elpd = purrr::map(dw_loo, ~ pluck(., 1, 1)), # extract elpd for DW model
         dw_SE_elpd = purrr::map(dw_loo, ~ pluck(., 1, 4)), # extract SE of elpd for DW model
         lw_elpd = purrr::map(lw_loo, ~ pluck(., 1, 1)), # extract elpd for LW model
         lw_SE_elpd = purrr::map(lw_loo, ~ pluck(., 1, 4)), # extract elpd for LW model
         elpd_diff = purrr::map(loo_comp, ~ pluck(., 2)), # extract the elpd diff value generated by loo_compare()
         SE_diff = purrr::map(loo_comp, ~ pluck(., 4))) %>% # extract the SE of elpd diff generated by loo_compare()
  select(-dw_loo, -lw_loo, -loo_comp) %>% # remove certain columns
  rowwise() %>%
  mutate(elpd_preferred = if_else(dw_elpd < lw_elpd, "Long-term", "Decision"), # identify the preferred model as the one with the largest ELPD
          elpd_diff_model =  # get difference in elpd that will serve as input into a subsequent trait model with HWI
                if_else(elpd_preferred == "Long-term", -1*abs(elpd_diff), abs(elpd_diff))) # if the long-term model is preferred, we want the difference to be negative, and positive if the decision model is preferred

View(elpd_SE)

# obtain WAIC and SE of WAIC for the decision window and long term model for each species
waic_SE <- models_df %>%
  mutate(waic_dw = purrr::map(dw_model, ~loo::waic(.x)), # use waic function in loo package on DW model
         waic_lw = purrr::map(lw_model, ~loo::waic(.x)), # use waic function in loo package on LW model
         dw_waic = purrr::map(waic_dw, ~pluck(., 1, 3)), # extract waic for DW model
         dw_SE_waic = purrr::map(waic_dw, ~pluck(., 1, 6)), # extract SE of waic for DW model
         lw_waic = purrr::map(waic_lw, ~pluck(., 1, 3)), # extract waic for LW model
         lw_SE_waic = purrr::map(waic_lw, ~pluck(., 1, 6)), # extract SE of waic for LW model
  ) %>%
  select(-dw_model, -lw_model, -waic_dw, -waic_lw) %>% # remove certain columns
  rowwise() %>%
  mutate(waic_diff = if_else(dw_waic < lw_waic, # obtain the difference in waic between the "preferred" model and the other model
                             (lw_waic - dw_waic), 
                             (dw_waic - lw_waic)),
         waic_preferred = if_else(dw_waic > lw_waic, "Long-term", "Decision"), # identify the preferred model as the one with the smallest waic
         waic_diff_model = # get difference in waic that will serve as input into a subsequent trait model with HWI
           if_else(waic_preferred == "Long-term", -1*abs(waic_diff), abs(waic_diff))) # if the long-term model is preferred, we want the difference to be negative, and positive if the decision model is preferred

# note: in the above section of code, we do not use loo_compare to compare the two models as the output of this function does not present differences based on waic values
# instead, we manually calculate the difference in waic between the two models (stored in the column waic_diff)
# unlike elpd, the preferred model is the one with the lower waic
# lastly, we do not obtain the difference in the SE of waic. For elpd (above), the difference in SE provided by loo_compare() is not derived by simply subtracting the two SE values for the models
# As we can't easily calculate this value for waic, we leave it out of this data frame

View(waic_SE)

# export results
saveRDS(elpd_SE, here("Outputs", "elpd_SE.rds"))
saveRDS(waic_SE, here("Outputs", "waic_SE.rds"))
